# --------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024 Jayesh Badwaik <jayesh@ambhora.com>
# --------------------------------------------------------------------------------------------------

[website]
baseURL = 'https://mori-org.github.io/'
title = "mori"
description = 'A Static Site Generator for Technical Writing'
languageCode = 'en-us'
license="CC-BY-4.0"

[theme]
name = "morshi"

